json.id listing.id
json.lister_id listing.lister_id
json.listing_title listing.listing_title
json.make_id listing.make_id
json.model_id listing.model_id
json.category_id listing.category_id
json.condition listing.condition
json.price listing.price
json.location listing.location
json.color listing.color
json.year_made listing.year_made
json.description listing.description
json.watcher_count listing.watcher_count
json.created_at listing.created_at
json.updated_at listing.updated_at
